### ISSUE TITLE
Add port pillar for exporter

### ISSUE THREAD

**Issue by MalloZup** [SUSE/sapnwbootstrap-formula#39]
In the future, I would add the option to select the port and log level from the formula.

for sap_host_exporter

**Comment by MalloZup** [comment]
@stefanotorresi It might be a easy fix for you to get started with formulas.

**Comment by stefanotorresi** [comment]
roger! I'm afraid I won't have the capacity for this sprint, but I will certainly look into it maybe the next one!

**Comment by stefanotorresi** [comment]
closing: we use local UDS so TCP settings are no longer relevant.
