### ISSUE TITLE
improve documentation

### ISSUE THREAD

**Issue by MalloZup** [SUSE/sapnwbootstrap-formula#5]
I think that even if the formula is at begin, we should improve the documentation from the begin.

Currenlty the readme doesn't provide any info.

We should make clear statement about the specifications of the formula, it's behaviour, it's input (pillar) and how it is supposed to work 

If there is already a `pillar` example, I assume that it should already work, so we should start to document asap :grin: hth

**Comment by arbulu89** [comment]
Totally agree that the lack of documentation is a big issue. I promise that I will add the required docs when the formula is ready to be used. Right now it only offers extremely basic functions...
I would even say that it shouldn't be used in the current state hehe
Anyway, I will resume now the implementation of the new features, and as far as I progress and see that the first real release of the formula is ready, I will add all the docs!
Thanks for the reminder anyway!

**Comment by arbulu89** [comment]
https://github.com/SUSE/sapnwbootstrap-formula/pull/12
