### ISSUE TITLE
virtual ip adresses used in the pillar are not persistent

### ISSUE THREAD

**Issue by petersatsuse** [SUSE/sapnwbootstrap-formula#73]
if the formula is used standalone and without a cluster, the virtual ip addresses used for the different sap instances (as,er,db,pas,aas, ...) are gone after a reboot.

They are not persistence as they are not written into the /etc/icfg- file.

They simply need to be append to the /etc/sysconfig/network/ifcfg-ethX file like
 IPADDR_1=192.168.201.115/24 
 IPADDR_2=192.168.201.116/24 
 IPADDR_3=192.168.201.117/24 
 IPADDR_4=192.168.201.118/24 
...

**Comment by arbulu89** [comment]
@stefanotorresi FYI

**Comment by arbulu89** [comment]
@petersatsuse How can be reproduce the error created by this and check if the potential fix solves it?
Do you check if the SAP instances are working after a reboot? Do we need to run certain command or check logs?

**Comment by petersatsuse** [comment]
To reproduce, simply install a NW without a cluster. 

The formula creates somehow the virtual interfaces, so the install runs. 
But if you reboot the system, you SAP system can not start anymore as there are no network interfaces for the virtual ip's.

In a cluster environment the virtual ip's are generated and controlled by the cluster-stack and therefore everything is ok.
Using it without a cluster, only work until you reboot the first time.

I proofed that adding the virt. ip to the ifcfg file makes them persistent, and i am able to start the sap system (what was not possible before)

**Comment by arbulu89** [comment]
Fixed by: https://github.com/SUSE/sapnwbootstrap-formula/pull/81
