### ISSUE TITLE
The formula could not be used without a NFS-share

### ISSUE THREAD

**Issue by petersatsuse** [SUSE/sapnwbootstrap-formula#74]
As in a distributed sap architecture and with HA we use a NFS-share for the NW profiles etc.
If the formula is not used in the above context, like single node/dual node deployment, the NFS part in the pillar and in the formula need to be manual deleted/uncommented before the deployment can start
It would be helpful to have a switch for such a usage without a nfs-share

**Comment by arbulu89** [comment]
Fixed in: https://github.com/SUSE/sapnwbootstrap-formula/pull/79
